export const API = '/api/'
export const SWAGGER = 'api-docs'
export const RURAL_PRODUCERS = 'rural-producers'
export const TOTAL_FARMS = '/total-farms'
export const STATE = '/state'
export const CROP = '/crop'
export const LAND_USE = '/land_use'
export const DASHBOARD = 'dashboard'
